apiVersion: apps/v1
kind: Deployments
metadata:
  name: jsrpc
  labels:
    app: jsrpc
spec:
  replicas: 3
  template:
    metadata:
      name: jsrpc
      labels:
        app: jsrpc
    spec:
      containers:
        - name: jsrpc
          image:
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: jsrpc

---
apiVersion: v1
kind: Service
metadata:
  name:
spec:
  selector:
    app:
  ports:
    - port: 8080
  type: NodePort